name: 'Python liccheck'
description: 'Helps to check and manage licenses of required python dependencies using liccheck'
author: rsitro-chrono
branding:
  icon: 'shield'
  color: 'green'
runs:
  using: 'docker'
  image: 'Dockerfile'